import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <div>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link href="https://fonts.googleapis.com/css2?family=Barlow&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Cairo&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Coda&family=Fira+Sans&family=Dancing+Script&family=Kay+Pho+Du&family=Spirax&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Barlow&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Abel&family=Cantora+One&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Sacramento&display=swap" rel="stylesheet" />
                <link href="https://fonts.googleapis.com/css2?family=Bad+Script&display=swap" rel="stylesheet" />

                <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.5.1/css/all.css" />
                <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.5.1/css/sharp-light.css" />
                <link href="https://fonts.googleapis.com/css2?family=Protest+Revolution&display=swap" rel="stylesheet" />
           
                <body className="bg-[#fbf6f2] {inter.className}">{children}</body>
       </div>
    </html>
  );
}
