import type { Metadata } from "next";
import { Inter, Cousine, Poppins, Nunito } from "next/font/google";

import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">          
      <body className={`bg-[#fbf6f2] ${nunito.variable}`}>{children}</body>
    </html>
  );
}
